// Locale-aware display names for page slugs and skeleton component/section
// ids — compose-content.ts's humanizeSlug(slug) is otherwise the *only*
// source for a page's title and every auto-built section's heading
// ("Games", "Welcome Offer", "How To Register", ...), and it always
// produces English regardless of the site's locale. This table lets
// compose-content.ts (and assemble-site.ts, for legal page titles) look up
// a real translation first, falling back to humanizeSlug's English output
// for any locale/slug this table doesn't cover — same fallback posture as
// casino-v1-translations.ts's translate().
//
// Keys cover every id compose-content.ts ever calls humanizeSlug() with:
// the page slugs in DEFAULT_PAGE_SLUGS + the six legal slugs (assembleSite's
// LEGAL_PAGE_LABELS), and every component/section id referenced across
// content-library/skeletons/*.json. A handful of ids are used as both a
// page slug and a section id (e.g. "registration") — they want the same
// translated word either way, so one flat table per locale is enough.
type LabelDictionary = Record<string, string>;

const de: LabelDictionary = {
  index: "Startseite",
  review: "Bewertung",
  bonus: "Bonus",
  withdrawal: "Auszahlung",
  slots: "Slots",
  login: "Anmeldung",
  application: "Konto erstellen",
  registration: "Registrierung",
  "no-deposit-bonus": "Bonus ohne Einzahlung",
  "free-spins": "Freispiele",
  "promo-code": "Aktionscode",
  "privacy-policy": "Datenschutzerklärung",
  "cookies-policy": "Cookie-Richtlinie",
  "terms-conditions": "Allgemeine Geschäftsbedingungen",
  "betting-rules": "Spielregeln",
  "responsible-gaming": "Verantwortungsvolles Spielen",
  contacts: "Kontakt",
  "account-access": "Kontozugang",
  "bonus-signup": "Bonus bei Anmeldung",
  cta: "Jetzt mitmachen",
  eligibility: "Teilnahmebedingungen",
  "eligible-games": "Teilnahmeberechtigte Spiele",
  faq: "Häufige Fragen",
  "forgot-password": "Passwort vergessen",
  games: "Spiele",
  "how-to-claim": "Bonus einlösen",
  "how-to-login": "Anmeldevorgang",
  "how-to-play": "Spielanleitung",
  "how-to-register": "Registrierungsablauf",
  intro: "Übersicht",
  jackpots: "Jackpots",
  mobile: "Mobil",
  "mobile-play": "Mobiles Spielen",
  payments: "Zahlungen",
  privacy: "Datenschutz",
  "pros-cons": "Vor- und Nachteile",
  providers: "Anbieter",
  "rating-breakdown": "Bewertungsübersicht",
  rtp: "Auszahlungsquote (RTP)",
  security: "Sicherheit",
  support: "Kundensupport",
  terms: "Bedingungen",
  troubleshooting: "Problemlösung",
  "two-factor-authentication": "Zwei-Faktor-Authentifizierung",
  verdict: "Fazit",
  verification: "Verifizierung",
  volatility: "Volatilität",
  "welcome-offer": "Willkommensangebot",
  "where-to-enter": "Wo eingeben",
  "withdrawal-limits": "Auszahlungslimits",
  withdrawals: "Auszahlungen",
};

const nl: LabelDictionary = {
  index: "Home",
  review: "Beoordeling",
  bonus: "Bonus",
  withdrawal: "Uitbetaling",
  slots: "Slots",
  login: "Inloggen",
  application: "Account aanmaken",
  registration: "Registratie",
  "no-deposit-bonus": "Bonus zonder storting",
  "free-spins": "Gratis spins",
  "promo-code": "Promotiecode",
  "privacy-policy": "Privacybeleid",
  "cookies-policy": "Cookiebeleid",
  "terms-conditions": "Algemene voorwaarden",
  "betting-rules": "Spelregels",
  "responsible-gaming": "Verantwoord spelen",
  contacts: "Contact",
  "account-access": "Accounttoegang",
  "bonus-signup": "Bonus bij aanmelding",
  cta: "Doe nu mee",
  eligibility: "Voorwaarden",
  "eligible-games": "In aanmerking komende games",
  faq: "Veelgestelde vragen",
  "forgot-password": "Wachtwoord vergeten",
  games: "Games",
  "how-to-claim": "Bonus claimen",
  "how-to-login": "Inlogproces",
  "how-to-play": "Spelinstructies",
  "how-to-register": "Registratieproces",
  intro: "Overzicht",
  jackpots: "Jackpots",
  mobile: "Mobiel",
  "mobile-play": "Mobiel spelen",
  payments: "Betalingen",
  privacy: "Privacy",
  "pros-cons": "Voor- en nadelen",
  providers: "Providers",
  "rating-breakdown": "Beoordelingsoverzicht",
  rtp: "Uitkeringspercentage (RTP)",
  security: "Beveiliging",
  support: "Klantenservice",
  terms: "Voorwaarden",
  troubleshooting: "Probleemoplossing",
  "two-factor-authentication": "Tweestapsverificatie",
  verdict: "Conclusie",
  verification: "Verificatie",
  volatility: "Volatiliteit",
  "welcome-offer": "Welkomstaanbieding",
  "where-to-enter": "Waar in te voeren",
  "withdrawal-limits": "Uitbetalingslimieten",
  withdrawals: "Uitbetalingen",
};

const fi: LabelDictionary = {
  index: "Etusivu",
  review: "Arvostelu",
  bonus: "Bonus",
  withdrawal: "Kotiutus",
  slots: "Kolikkopelit",
  login: "Kirjaudu sisään",
  application: "Tilin luonti",
  registration: "Rekisteröityminen",
  "no-deposit-bonus": "Talletukseton bonus",
  "free-spins": "Ilmaiskierrokset",
  "promo-code": "Kampanjakoodi",
  "privacy-policy": "Tietosuojakäytäntö",
  "cookies-policy": "Evästekäytäntö",
  "terms-conditions": "Käyttöehdot",
  "betting-rules": "Pelisäännöt",
  "responsible-gaming": "Vastuullinen pelaaminen",
  contacts: "Yhteystiedot",
  "account-access": "Tilin käyttö",
  "bonus-signup": "Rekisteröitymisbonus",
  cta: "Liity nyt",
  eligibility: "Kelpoisuusehdot",
  "eligible-games": "Osallistuvat pelit",
  faq: "Usein kysytyt kysymykset",
  "forgot-password": "Unohtunut salasana",
  games: "Pelit",
  "how-to-claim": "Bonuksen lunastaminen",
  "how-to-login": "Kirjautumisohjeet",
  "how-to-play": "Pelaamisohjeet",
  "how-to-register": "Rekisteröitymisohjeet",
  intro: "Yleiskatsaus",
  jackpots: "Jättipotit",
  mobile: "Mobiili",
  "mobile-play": "Mobiilipelaaminen",
  payments: "Maksut",
  privacy: "Tietosuoja",
  "pros-cons": "Hyvät ja huonot puolet",
  providers: "Pelivalmistajat",
  "rating-breakdown": "Arvostelun erittely",
  rtp: "Takaisinmaksuprosentti (RTP)",
  security: "Turvallisuus",
  support: "Asiakastuki",
  terms: "Ehdot",
  troubleshooting: "Vianmääritys",
  "two-factor-authentication": "Kaksivaiheinen tunnistautuminen",
  verdict: "Yhteenveto",
  verification: "Tunnistautuminen",
  volatility: "Volatiliteetti",
  "welcome-offer": "Tervetuliaistarjous",
  "where-to-enter": "Mistä syöttää",
  "withdrawal-limits": "Kotiutusrajat",
  withdrawals: "Kotiutukset",
};

const sv: LabelDictionary = {
  index: "Hem",
  review: "Recension",
  bonus: "Bonus",
  withdrawal: "Uttag",
  slots: "Spelautomater",
  login: "Logga in",
  application: "Skapa konto",
  registration: "Registrering",
  "no-deposit-bonus": "Bonus utan insättning",
  "free-spins": "Free spins",
  "promo-code": "Kampanjkod",
  "privacy-policy": "Integritetspolicy",
  "cookies-policy": "Cookiepolicy",
  "terms-conditions": "Villkor",
  "betting-rules": "Spelregler",
  "responsible-gaming": "Ansvarsfullt spelande",
  contacts: "Kontakt",
  "account-access": "Kontoåtkomst",
  "bonus-signup": "Registreringsbonus",
  cta: "Gå med nu",
  eligibility: "Villkor för deltagande",
  "eligible-games": "Kvalificerade spel",
  faq: "Vanliga frågor",
  "forgot-password": "Glömt lösenord",
  games: "Spel",
  "how-to-claim": "Hämta bonusen",
  "how-to-login": "Så loggar du in",
  "how-to-play": "Spelinstruktioner",
  "how-to-register": "Registreringsprocess",
  intro: "Översikt",
  jackpots: "Jackpottar",
  mobile: "Mobil",
  "mobile-play": "Mobilspel",
  payments: "Betalningar",
  privacy: "Integritet",
  "pros-cons": "För- och nackdelar",
  providers: "Spelleverantörer",
  "rating-breakdown": "Betygsöversikt",
  rtp: "Återbetalningsprocent (RTP)",
  security: "Säkerhet",
  support: "Kundsupport",
  terms: "Villkor",
  troubleshooting: "Felsökning",
  "two-factor-authentication": "Tvåfaktorsautentisering",
  verdict: "Slutsats",
  verification: "Verifiering",
  volatility: "Volatilitet",
  "welcome-offer": "Välkomsterbjudande",
  "where-to-enter": "Var du anger den",
  "withdrawal-limits": "Uttagsgränser",
  withdrawals: "Uttag",
};

const dictionaries: Record<string, LabelDictionary> = { de, nl, fi, sv };

// Same locale-resolution as casino-v1-translations.ts's translate(): exact
// code first (a future "pt-BR"-vs-"pt-PT" split could still override the
// bare subtag), then the subtag before the first "-". Returns undefined
// (not English text) when nothing matches, so callers can fall back to
// humanizeSlug(slug) themselves rather than this module hardcoding what
// that fallback looks like.
export function localizedLabel(locale: string, slug: string): string | undefined {
  const languageSubtag = locale.split("-")[0];
  const dictionary = dictionaries[locale] ?? dictionaries[languageSubtag];
  return dictionary?.[slug];
}
